#!/usr/bin/python3


import sys
import winsound

def sound():
    winsound.Beep(1000, 100)
    winsound.Beep(700, 50)
    winsound.Beep(1000, 100)
    winsound.Beep(700, 50)


def board(intdata):
    winsound.Beep(1000,100)
    print('\n'*100)
    print("***TIC TAC TOE***")
    print("-----------------")
    print(" " * 5 + '|' + " " * 5 + '|' + " " * 5)
    print(" " * 2 + intdata[1] + " " * 2 + '|' + " " * 2 + intdata[2] + " " * 2 + '|' + " " * 2 + intdata[3] + " " * 2)
    print(" " * 5 + '|' + " " * 5 + '|' + " " * 5)
    print("-----------------")
    print(" " * 5 + '|' + " " * 5 + '|' + " " * 5)
    print(" " * 2 + intdata[4] + " " * 2 + '|' + " " * 2 + intdata[5] + " " * 2 + '|' + " " * 2 + intdata[6] + " " * 2)
    print(" " * 5 + '|' + " " * 5 + '|' + " " * 5)
    print("-----------------")
    print(" " * 5 + '|' + " " * 5 + '|' + " " * 5)
    print(" " * 2 + intdata[7] + " " * 2 + '|' + " " * 2 + intdata[8] + " " * 2 + '|' + " " * 2 + intdata[9] + " " * 2)
    print(" " * 5 + '|' + " " * 5 + '|' + " " * 5)
    print("-----------------")

def xfunc(x):

    for i in range(1, len(intdata)):
        if i == x and intdata[i] == '0' or x > 9 or x == 0:
            print("Same position cannot be selected twice | Select numbers from 1 to 9")
            return 'X'
        elif i == x and intdata[i] != '0':
            intdata[i] = 'X'
            board(intdata)
            if ''.join(intdata[1:4]) == 'XXX' or ''.join(intdata[4:7]) == 'XXX' or ''.join(intdata[7:]) == 'XXX':
                print("\n *****X WINS****")
                sound()
                sys.exit()
            elif ''.join(intdata[1:8:3]) == 'XXX' or ''.join(intdata[2:9:3]) == 'XXX' or ''.join(intdata[3:10:3]) == 'XXX':
                print("\n *****X WINS****")
                sound()
                sys.exit()
            elif ''.join(intdata[1:10:4]) == 'XXX' or ''.join(intdata[3:8:2]) == 'XXX':
                print("\n *****X WINS****")
                sound()
                sys.exit()



def ofunc(o):

    for i in range(1, len(intdata)):
        if i == o and intdata[i] == 'X' or o > 9 or o == 0:
            print("Same position cannot be selected twice | Select numbers from 1 to 9")
            return '0'
        elif i == o and intdata[i] != 'X':
            intdata[i] = '0'
            board(intdata)
            if ''.join(intdata[1:4]) == '000' or ''.join(intdata[4:7]) == '000' or ''.join(intdata[7:]) == '000':
                print("\n *****0 WINS****")
                sound()
                sys.exit()
            elif ''.join(intdata[1:8:3]) == '000' or ''.join(intdata[2:9:3]) == '000' or ''.join(intdata[3:10:3]) == '000':
                print("\n *****0 WINS****")
                sound()
                sys.exit()
            elif ''.join(intdata[1:10:4]) == '000' or ''.join(intdata[3:8:2]) == '000':
                print("\n *****0 WINS****")
                sound()
                sys.exit()


intdata = [' ']*10
board(intdata)
xo = input("Choose X or 0: ")

if xo.lower() == 'x':

        while True:

          x_numbers = int(input("Please X enter number from 1-9: "))
          status_x = xfunc(x_numbers)

          while  status_x == 'X':
              x_numbers = int(input("Please X enter number from 1-9: "))
              status_x = xfunc(x_numbers)

          zero_numbers = int(input("Please 0 enter number from 1-9: "))
          status_zero = ofunc(zero_numbers)

          while status_zero == '0':
              zero_numbers = int(input("Please 0 enter number from 1-9: "))
              status_zero = ofunc(zero_numbers)


elif xo == '0':

        while True:

            zero_numbers = int(input("Please 0 enter number from 1-9: "))
            status_zero = ofunc(zero_numbers)

            while status_zero == '0':
                zero_numbers = int(input("Please 0 enter number from 1-9: "))
                status_zero = ofunc(zero_numbers)

            x_numbers = int(input("Please X enter number from 1-9: "))
            status_x = xfunc(x_numbers)

            while status_x == 'X':
                x_numbers = int(input("Please X enter number from 1-9: "))
                status_x = xfunc(x_numbers)






